# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-10 08:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0002_business'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_pi',
            new_name='profile_pic',
        ),
    ]
