# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-11 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0006_post_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
