# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-12 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0008_auto_20190112_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='image',
            field=models.ImageField(null=True, upload_to='image'),
        ),
    ]
